fix: `toString` PID number for `writeFileSync` (second arg requires string) (#573)
Node 14 will no longer coerce incorrect types given to `writeFileSync`.

The error thrown:

```
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number
```